### ISSUE TITLE
Spatio-Temporal-Aware Embedding

### ISSUE THREAD

**Issue by serycjon** [yuhuayc/fast-vos#2]
Hi, in the paper, you say that: _"we add the spatial coordinates and frame number as additional inputs
to the embedding head"_, however this does not seem to be present in the code (I have studied demo_interactive.m and deploy.prototxt).  Is that correct?

Would you please provide the mentioned improvements to the repo or at least comment a bit on how it was done?  In particular, do you just add two more input channels to the last convolutional layer (``conv_metric``), one channel filled with the frame number and the other one with pixel coordinates?  If so, how do you represent the pixel coordinates (float [-1, 1], [0, 1], int [0, pixel_resolution], ...)?

**Comment by yuhuayc** [comment]
Yes, we do not use the spatial&temporal for interactive setting, this part will be provided soon with the semi-supervised settings.

Basically it's implemented as three channels (x,y,frame), all normalized to [0,1].

**Comment by yuhuayc** [comment]
Thanks for the message.

Yes, we do not use the spatial&temporal for interactive setting, this part will be provided soon with the semi-supervised settings.

Basically it's implemented as three channels (x,y,frame), all normalized to [0,1].
